### ISSUE TITLE
add link to bug tracker to META.yml

### ISSUE THREAD

**Issue by chorny** [estrabd/Image-Libpuzzle#3]
In Makefile.PL:
```
resources => {
  bugtracker  => {
    web    => 'https://github.com/estrabd/Image-Libpuzzle/issues/',
  },
}
```
See https://metacpan.org/pod/CPAN::Meta::Spec#resources

**Comment by estrabd** [comment]
Thank you, @chorny.  I didn't mean to be harsh there and I appreciate your efforts, I will take care of this soon.

**Comment by estrabd** [comment]
done by @benkasminbullock - thank you!
